version: '3'
# services
services:
  
  # Symfony service to provide api
  php-apache:
    container_name: php-apache
    image: webdevops/php-apache-dev:7.3
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
    ports:
      - 8080:80
    links:
      - mysql-apache

  mysql-apache:
    container_name: mysql-apache
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prova
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123.456